export const ENV_INJECT_MIN_SCORE = "CCMEM_INJECT_MIN_SCORE";
export const ENV_LINK_BOOST = "CCMEM_LINK_BOOST";
export const ENV_INJECT_LOG = "CCMEM_INJECT_LOG";
export const ENV_BLOCK_AFTER = "CCMEM_BLOCK_AFTER";
export const ENV_BLOCK_DRIFT = "CCMEM_BLOCK_DRIFT";
export const ENV_GATE_DISABLE = "CCMEM_GATE_DISABLE";
export const ENV_LOG_LEVEL = "CCMEM_LOG_LEVEL";

export const INJECT_LOG_DISABLED_VALUE = "0";
export const GATE_DISABLED_VALUE = "1";

export const INJECT_MIN_SCORE_DEFAULT = 0.2;
export const LINK_BOOST_DEFAULT = 0.003;
export const BLOCK_AFTER_DEFAULT = 2;
export const BLOCK_DRIFT_DEFAULT = 5;
